name: objectdb
description: Flutter NoSQL Database
version: 0.0.1
author: Team netz.chat <dev@netz.chat>
homepage: https://github.com/netz-chat/objectdb

dependencies:
  flutter:
    sdk: flutter

  execution_queue:
    git: git://github.com/netz-chat/execution_queue.git

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: