name: objectdb
description: Persistent embedded NoSQL database for Dart and Flutter. 100% Dart.
version: 0.0.7
author: Team netz.chat <dev@netzchat.com>
homepage: https://github.com/netz-chat/objectdb
environment:
    sdk: '>=2.0.0-dev.1.2 <2.0.0'

dependencies:
  execution_queue: ^0.0.2

dev_dependencies:
  test: any
